### ISSUE TITLE
Issueを作成するときエラー

### ISSUE THREAD

**Issue by kmiyake** [timecard/timecard-rails#141]
```
NoMethodError (undefined method `oauth_token' for nil:NilClass):
  app/models/authentication.rb:16:in `get_chatwork_token'
  app/models/chatwork.rb:6:in `post'
  app/controllers/issues_controller.rb:49:in `block in create'
  app/controllers/issues_controller.rb:45:in `create'


  Rendered /Users/kotamiyake/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.8ms)
  Rendered /Users/kotamiyake/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.3ms)
  Rendered /Users/kotamiyake/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.1ms)
  Rendered /Users/kotamiyake/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (25.5ms)
```

現在は無条件でChatwork APIを叩きにいっているため、Chatwork APIの認証が行われていない場合はエラーとなる。認証が行われていない場合には処理を迂回するよう修正する。

**Comment by kmiyake** [comment]
参照場所を間違えました。#146は関係無いです。
